# Generated by Django 4.2.4 on 2023-08-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('first_surname', models.CharField(max_length=30)),
                ('second_surname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('identification', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('minutes_spent', models.IntegerField()),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
    ]
