# Generated by Django 4.2.4 on 2023-08-22 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cliente_date_remove_cliente_minutes_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='registros',
            field=models.ManyToManyField(related_name='clientes_registrados', to='api.registrocliente'),
        ),
        migrations.AlterField(
            model_name='registrocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_cliente', to='api.cliente'),
        ),
    ]
