# Generated by Django 4.2.4 on 2023-08-22 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_registros'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes_spent', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='registros',
        ),
        migrations.DeleteModel(
            name='RegistroCliente',
        ),
        migrations.AddField(
            model_name='controltiempo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_tiempo', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cotrol_tiempo',
            field=models.ManyToManyField(related_name='control_tiempo', to='api.controltiempo'),
        ),
    ]
