# Generated by Django 4.2.4 on 2023-09-03 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usuario_usuariotiempo_usuario_usuario_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='handleColor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='handleColor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_tiempo',
            field=models.ManyToManyField(related_name='control_tiempo', to='api.usuariotiempo'),
        ),
        migrations.AlterField(
            model_name='usuariotiempo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_tiempo', to='api.usuario'),
        ),
    ]
