# Generated by Django 4.2.4 on 2023-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_cotrol_tiempo_cliente_usuario_tiempo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='consentNumber',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='handleColor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='consentNumber',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='handleColor',
        ),
        migrations.AddField(
            model_name='controltiempo',
            name='consentNumber',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='controltiempo',
            name='handleColor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usuariotiempo',
            name='consentNumber',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usuariotiempo',
            name='handleColor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
