# Generated by Django 4.2.4 on 2023-09-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_usuario_usuario_tiempo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='second_surname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='controltiempo',
            name='consentNumber',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='controltiempo',
            name='handleColor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='second_surname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
