# Generated by Django 4.2.4 on 2023-09-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cliente_second_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='annotations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='annotations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
