# Generated by Django 4.2.4 on 2023-09-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cliente_annotations_usuario_annotations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='annotations',
        ),
        migrations.AddField(
            model_name='controltiempo',
            name='annotations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuariotiempo',
            name='annotations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
